### ISSUE TITLE
crash on Android trying to open an Android app

### ISSUE THREAD

**Issue by PureNukage** [YoYoGames/GameMaker-HTML5#60]
I was trying to have an app running in-browser and having it open another app on the Android and ran into a crash

```
--------- beginning of crash
09-14 13:36:00.953 14242 14266 E AndroidRuntime: FATAL EXCEPTION: GLThread 35
09-14 13:36:00.953 14242 14266 E AndroidRuntime: Process: com.company.game, PID: 14242
09-14 13:36:00.953 14242 14266 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
09-14 13:36:00.953 14242 14266 E AndroidRuntime:     at com.yoyogames.runner.RunnerJNILib.Process(Native Method)
09-14 13:36:00.953 14242 14266 E AndroidRuntime:     at com.company.game.DemoRenderer.onDrawFrame(DemoRenderer.java:500)
09-14 13:36:00.953 14242 14266 E AndroidRuntime:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1573)
09-14 13:36:00.953 14242 14266 E AndroidRuntime:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
```

**Comment by nkrapivin** [comment]
Your issue is not related to the HTML5 runner, you crashed in the Android runner, please report this as a normal bug through YYG Contact form.
